version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_clientes
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Guayaquil
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red-clientes

  app:
    build: .
    container_name: clientes_app
    depends_on:
      - postgres
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - red-clientes

volumes:
  postgres_data:

networks:
  red-clientes: