apiVersion: v1
kind: Service
metadata:
  name: cliente-microservicio
  namespace: clientes
spec:
  type: LoadBalancer
  selector:
    app: cliente-microservicio
  ports:
    - port: 80
      targetPort: 8081