name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Descargar el c√≥digo
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Configurar Java (necesario para Maven)
      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3Ô∏è‚É£ Compilar el proyecto (CREA target/*.jar)
      - name: Compilar con Maven
        run: mvn clean package -DskipTests



      # üîç DEBUG (AQU√ç, JUSTO AQU√ç)
      - name: DEBUG
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "USERNAME VACIO"
          else
            echo "USERNAME OK"
          fi

          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "PASSWORD VACIO"
          else
            echo "PASSWORD OK"
          fi

      # 4Ô∏è‚É£ Login en Docker Hub (con secrets)
      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5Ô∏è‚É£ Construir la imagen Docker
      - name: Build Docker Image
        run: docker build -t fredvlad/cliente-microservicio:latest .

      # 6Ô∏è‚É£ Subir la imagen a Docker Hub
      - name: Push Docker Image
        run: docker push fredvlad/cliente-microservicio:latest