name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar el código
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java (necesario para Maven)
      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Compilar el proyecto (CREA target/*.jar)
      - name: Compilar con Maven
        run: mvn clean package -DskipTests





      # 4️⃣ Login en Docker Hub (con secrets)
      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 5️⃣ Construir la imagen Docker
      - name: Build Docker Image
        run: docker build -t fredvlad/cliente-microservicio:latest .

      # 6️⃣ Subir la imagen a Docker Hub
      - name: Push Docker Image
        run: docker push fredvlad/cliente-microservicio:latest