name: ClienteMicroservice

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 3. Compilar con Maven
        run: mvn clean package -DskipTests

      - name: 4. Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 5. Build y Push de Imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ms-clientes:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ms-clientes:latest

      - name: 6. Despliegue en Azure vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_IP }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd ~/clientes
            docker-compose down
            docker-compose pull
            docker-compose up -d
